import re
from urllib.parse import urljoin
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time

def get_sitemap_url(base_url):
    return urljoin(base_url, "/sitemap.xml")

def extract_urls(base_url):
    sitemap_url = get_sitemap_url(base_url)

    options = Options()
    options.add_argument("--headless=new")
    options.add_argument("--disable-gpu")
    options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36")

    driver = None
    try:
        driver = webdriver.Chrome(options=options)
        driver.set_page_load_timeout(30)
        driver.get(sitemap_url)
        
        # Give JS a moment to render if it's a dynamic sitemap
        time.sleep(2)
        
        page_source = driver.page_source
        
        # Regex to find all <loc>...</loc> tags
        # This reliably handles raw XML or XML wrapped in HTML generated by Chrome.
        urls = re.findall(r'<loc[^>]*>\s*(.*?)\s*</loc>', page_source, re.IGNORECASE)
        
        if driver:
            driver.quit()

        # Remove duplicates
        unique_urls = list(dict.fromkeys(urls))

        # Check if we at least hit a real responsive page, otherwise the length is 0
        if not unique_urls:
            # Maybe it returned a 404 block or text format without <loc> tags
            # We can check if page title indicates 404
            if "404" in driver.title or "Not Found" in driver.title:
                 return {"error": "404 Client Error: Not Found for url: " + sitemap_url, "urls": []}

        return {"error": None, "urls": unique_urls}
        
    except Exception as e:
        if driver:
            try:
                driver.quit()
            except:
                pass
        return {"error": str(e), "urls": []}